- lib/diaspora_federation/entities.rb
- lib/diaspora_federation/entities/comment.rb
- lib/diaspora_federation/entities/like.rb
- lib/diaspora_federation/entities/message.rb
- lib/diaspora_federation/entities/participation.rb
- lib/diaspora_federation/entities/poll_participation.rb
- lib/diaspora_federation/entities/relayable.rb
- lib/diaspora_federation/validators.rb
- lib/diaspora_federation/validators/comment_validator.rb
- lib/diaspora_federation/validators/like_validator.rb
- lib/diaspora_federation/validators/message_validator.rb
- lib/diaspora_federation/validators/participation_validator.rb
- lib/diaspora_federation/validators/poll_participation_validator.rb
- lib/diaspora_federation/validators/relayable_validator.rb
- spec/factories.rb
- spec/lib/diaspora_federation/entities/conversation_spec.rb
- spec/lib/diaspora_federation/entities/poll_participation_spec.rb
- spec/lib/diaspora_federation/validators/comment_validator_spec.rb
- spec/lib/diaspora_federation/validators/like_validator_spec.rb
- spec/lib/diaspora_federation/validators/message_validator_spec.rb
- spec/lib/diaspora_federation/validators/participation_validator_spec.rb
- spec/lib/diaspora_federation/validators/poll_participation_validator_spec.rb
- spec/support/shared_validator_specs.rb
Introduce the "Relayable" entity, which encapsulates common properties of entities that are inherited from Relayable class in the Diaspora source code - "parent_guid", "parent_author_signature", "author_signature".
> Introduce the "Relayable" entity

- lib/diaspora_federation.rb
- lib/diaspora_federation/entities/relayable.rb
- lib/diaspora_federation/properties_dsl.rb
- lib/diaspora_federation/salmon/xml_payload.rb
- lib/diaspora_federation/signing.rb
- spec/factories.rb
- spec/lib/diaspora_federation/entities/comment_spec.rb
- spec/lib/diaspora_federation/entities/conversation_spec.rb
- spec/lib/diaspora_federation/entities/like_spec.rb
- spec/lib/diaspora_federation/entities/message_spec.rb
- spec/lib/diaspora_federation/entities/participation_spec.rb
- spec/lib/diaspora_federation/entities/poll_participation_spec.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
- spec/lib/diaspora_federation/salmon/xml_payload_spec.rb
- spec/lib/diaspora_federation/signing_spec.rb
- spec/spec_helper.rb
- spec/support/shared_entity_specs.rb
- test/dummy/config/initializers/diaspora_federation.rb
This is a preliminary patch that implements signatures support for entities, the functionality that in Diaspora source represented by https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/encryptable.rb and friends.
It notably differs from the way it is done in Diaspora. The thing is that in [4269](https://github.com/diaspora/diaspora/pull/4269) and [4935](https://github.com/diaspora/diaspora/pull/4935) developers faced problem, that adding any new field to an entity would break backward compatibility with older diaspora implementations. That's why I moved signable_string to the XmlPayload class. There it will iterate every field in received Salmon during signature generation, no matter if an entity class aware of it or not.
This, though, forced me to move signatures update …
> Add signature computation for entities support

- .gitignore
- app/controllers/diaspora_federation/receive_controller.rb
- lib/diaspora_federation.rb
- lib/diaspora_federation/receiver.rb
- lib/diaspora_federation/receiver/private.rb
- lib/diaspora_federation/receiver/public.rb
- lib/diaspora_federation/salmon/encrypted_slap.rb
- lib/diaspora_federation/test/factories.rb
- spec/controllers/diaspora_federation/receive_controller_spec.rb
- spec/lib/diaspora_federation/receiver/private_spec.rb
- spec/lib/diaspora_federation/receiver/public_spec.rb
- spec/spec_helper.rb
- test/dummy/config/initializers/diaspora_federation.rb
Introduces DiasporaFederation::Postzord::Receive.
Probably lacks some tests.
> Receiving entities support

- lib/diaspora_federation/entities/message.rb
- lib/diaspora_federation/entities/poll_participation.rb
- lib/diaspora_federation/entities/relayable.rb
- lib/diaspora_federation/salmon/xml_payload.rb
- lib/diaspora_federation/test.rb
- spec/lib/diaspora_federation/entities/comment_spec.rb
- spec/lib/diaspora_federation/entities/like_spec.rb
- spec/lib/diaspora_federation/entities/message_spec.rb
- spec/lib/diaspora_federation/entities/participation_spec.rb
- spec/lib/diaspora_federation/entities/poll_participation_spec.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
Entities::Message requires "Conversation" at the place, for instance.
> Allow parent entity types different than "Post"

- lib/diaspora_federation/federation/sender/hydra_wrapper.rb
This patch sets CURLOPT_FORBID_REUSE, which tells cURL to close all connections when they are done. By default, connections are held open for later use unless explicitly closed or expired by a timeout. This can improve performance if the same instance is used for multiple requests to a single host.
We never have that: a host receives only one message per queue job, so keeping the socket opened for 60 seconds (the default timeout) is totally useless.
In addition, keeping the sockets open can cause problems for larger instances with fast workers and a lot of jobs. Mainly, https://github.com/diaspora/diaspora/issues/6485 is caused by this very issue, which is resolved by this as well.
This also **may** resolve some of the memory bloat described in …
> Do not reuse cURL sockets

- lib/diaspora_federation/discovery/host_meta.rb
- lib/diaspora_federation/entity.rb
- lib/diaspora_federation/federation/fetcher.rb
One should use \A and \z unless explicitly wants the line-wise behavior.
> Replace ^ and $ with \A \z in patterns

- lib/diaspora_federation/entities/message.rb
- lib/diaspora_federation/entity.rb
- lib/diaspora_federation/test/factories.rb
- spec/lib/diaspora_federation/entities/comment_spec.rb
- spec/lib/diaspora_federation/entities/conversation_spec.rb
- spec/lib/diaspora_federation/entities/like_spec.rb
- spec/lib/diaspora_federation/entities/message_spec.rb
- spec/lib/diaspora_federation/entities/participation_spec.rb
- spec/lib/diaspora_federation/entities/poll_participation_spec.rb
- spec/lib/diaspora_federation/entities/relayable_retraction_spec.rb
- spec/lib/diaspora_federation/entity_spec.rb
- spec/spec_helper.rb
- spec/support/shared_entity_specs.rb
By the results of the discussion at #42, there are changes to the `to_h` method.
Since `to_h` is intensively used for data generation for entity initializers in the `diaspora_federation` test suite, a move from `properties` to `enriched_properties` requires to uptade entity construction routine to support initialization of properties (boolean, integer, time) with string values.
> Use enriched_properties instead of properties in Entity#to_h

- test/scripts/travis.sh
For Ruby >= 2.2 travis.sh returned 0 even when the rspec test suite
has failed. This commit passes the return value from the test suite
as the CI script return value.
> Fix CI script false positive return code

- docs/index.md
Not obvious to know that the code is hosted at https://github.com/diaspora/diaspora_federation from the doc ;)
> Add a link to the source code

- docs/_entities/account_migration.md
- lib/diaspora_federation/entities.rb
- lib/diaspora_federation/entities/account_migration.rb
- lib/diaspora_federation/entities/relayable.rb
- lib/diaspora_federation/entities/signable.rb
- lib/diaspora_federation/test/factories.rb
- lib/diaspora_federation/validators.rb
- lib/diaspora_federation/validators/account_migration_validator.rb
- spec/lib/diaspora_federation/entities/account_migration_spec.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
- spec/lib/diaspora_federation/entities/signable_spec.rb
- spec/lib/diaspora_federation/validators/account_migration_validator_spec.rb
- spec/spec_helper.rb
A new entity to use when diaspora ID of a person has changed for some reason (e.g. account migration, pod hostname change, etc)
I'm still in doubts about the name. `AccountRename` may be confusing. "Rename" is not a very accurate word for what we do: we change the ID, replace one with another. But `IDChange` was criticised for using "ID" word which is confusing because of different kinds of IDs being used in diaspora. Opinions?
> AccountMigration entity

- lib/diaspora_federation/schemas/federation_entities.json
While there are some schemas ([1](http://json.schemastore.org/ninjs), [2](http://json.schemastore.org/xunit.runner.schema)) which do that, I found it rather problematic to work with versioned id when referring it from another schema.
JSON schema specification says that you're not actually expected to download schema from the URL when you want to refer it from other schema. It is more likely that you provide the schema out-of-band.
In Ruby with the gems we use it is possible to achive this using `JSON::Validator.add_schema` method call. It registers a schema and if the `Validator` then meets this schema referenced in another one, it uses the schema provided earlier.
While JSON schema specification says that a schema can be referenced with more than one ID, `JSON::Validator` actually uses …
> Don't use versioning in JSON schema id

- docs/_entities/profile.md
- lib/diaspora_federation/entities/profile.rb
- lib/diaspora_federation/test/factories.rb
- lib/diaspora_federation/validators/profile_validator.rb
- spec/lib/diaspora_federation/entities/account_migration_spec.rb
- spec/lib/diaspora_federation/entities/person_spec.rb
- spec/lib/diaspora_federation/entities/profile_spec.rb
- spec/lib/diaspora_federation/federation/receiver/public_spec.rb
- spec/lib/diaspora_federation/validators/profile_validator_spec.rb
Diaspora has this flag for some time now, but it is pod-local only. With this change we can also federate this information. We can also federate public profiles publicly, so public profiles with many contacts need to be federated only once (would be useful for the diaspora\* HQ account for example).
> Add public flag to profile entity

- lib/diaspora_federation/discovery/web_finger.rb
- lib/diaspora_federation/validators/web_finger_validator.rb
- spec/lib/diaspora_federation/discovery/web_finger_spec.rb
- spec/lib/diaspora_federation/validators/web_finger_validator_spec.rb
This makes the WebFinger generation more flexible, so it's better usable for other projects.
* It makes not needed properties optional for generation (was already optional for parsing).
* It allows to add additional elements (unrelated to the diaspora protocol).
Diaspora also needs this for OpenIDConnect when we switch to RFC7033 WebFinger (which will be the next step).
> Improve WebFinger generation

- lib/diaspora_federation/entities/comment.rb
- spec/lib/diaspora_federation/entities/comment_spec.rb
- spec/support/shared_entity_specs.rb
Since my [post on diaspora](https://nerdpol.ch/posts/635fb840f46f0134b8f952540061b601) some more podmins updated, so I think we can think about this again. I use the numbers from [the-federation.info](https://the-federation.info/diaspora), but subtracted the duplicates (librenet and datataffel).
We have currently 14970 active users last month and 14599 are on a pod with 0.6.3.0 or newer. That are 97.5%. That are 4% more than 2 Months ago. Until diaspora/diaspora#7436 gets merged to `develop` it'll still take some weeks (since we are still waiting for a friendica release and then + 2-3 weeks), so maybe even more podmins updates until then. (we can create another post or ask some podmins)
So 97.5% is OK for me, I don't think we need to wait longer. Any vetos? @denschub @svbergerem …
> Add created_at to comment

- lib/diaspora_federation/entities/event.rb
- lib/diaspora_federation/entities/photo.rb
- lib/diaspora_federation/entities/post.rb
- lib/diaspora_federation/entities/profile.rb
- lib/diaspora_federation/entities/relayable.rb
- lib/diaspora_federation/entities/reshare.rb
- lib/diaspora_federation/entities/status_message.rb
- lib/diaspora_federation/entity.rb
- lib/diaspora_federation/properties_dsl.rb
- lib/diaspora_federation/test/factories.rb
- spec/entities.rb
- spec/lib/diaspora_federation/entities/account_migration_spec.rb
- spec/lib/diaspora_federation/entities/person_spec.rb
- spec/lib/diaspora_federation/entities/profile_spec.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
- spec/lib/diaspora_federation/entities/status_message_spec.rb
- spec/lib/diaspora_federation/entity_spec.rb
- spec/lib/diaspora_federation/properties_dsl_spec.rb
- spec/support/shared_entity_specs.rb
There is no need to add empty elements for optional properties to the XML.
Refactoring:
* mark optional properties as `optional`
* use `nil` as default for optional properties
> Don't add optional properties to generated XML and JSON when nil

- lib/diaspora_federation/discovery/discovery.rb
- lib/diaspora_federation/discovery/exceptions.rb
- spec/lib/diaspora_federation/discovery/discovery_spec.rb
Always raise a `DiscoveryError` when something with the discovery fails
> Improve error handling for discovery errors

- docs/_includes/federation_tree.html
- docs/federation/diaspora_scheme.md
- docs/federation/types.md
- lib/diaspora_federation/entities/event.rb
- lib/diaspora_federation/entities/profile.rb
- lib/diaspora_federation/entity.rb
- lib/diaspora_federation/federation.rb
- lib/diaspora_federation/federation/diaspora_url_parser.rb
- lib/diaspora_federation/federation/fetcher.rb
- lib/diaspora_federation/federation/receiver/abstract_receiver.rb
- lib/diaspora_federation/validators/rules/guid.rb
- spec/lib/diaspora_federation/entities/account_migration_spec.rb
- spec/lib/diaspora_federation/entities/person_spec.rb
- spec/lib/diaspora_federation/entities/profile_spec.rb
- spec/lib/diaspora_federation/federation/diaspora_url_parser_spec.rb
- spec/lib/diaspora_federation/federation/receiver/private_spec.rb
- spec/lib/diaspora_federation/federation/receiver/public_spec.rb
- spec/lib/diaspora_federation/validators/rules/guid_spec.rb
This adds support to fetch linked entities from markdown text if they aren't already known to the server.
This is the first step needed for #75.
> Fetch posts linked with diaspora:// URLs

- lib/diaspora_federation/validators/rules/diaspora_id.rb
- spec/lib/diaspora_federation/validators/rules/diaspora_id_spec.rb
In a discussion with @SuperTux88, we discovered that our validation mechanism for diaspora\* IDs is not perfect. In the documentation, there are two additional rules currently not covered by the validator:
> The diaspora* ID is at most 255 chars long and it must be lowercase.
I altered the regex so that uppercased usernames and hostnames will fail the validation. This does not change our current behavior in reality, since diaspora\* already fails when using uppercase characters.
While working on it, I replaced the `letter`, `digit`, and `hexadecimal` parts with their POSIX character class counterparts. Ultimately, this should make the final expression more readable. Because the parts are named now anyway, I removed the individual variable definitions for them.
In addition, I added a check …
> Tighten the validation of diaspora* IDs

- docs/_entities/profile.md
- lib/diaspora_federation/federation/receiver/public.rb
- spec/lib/diaspora_federation/federation/receiver/public_spec.rb
This is needed to send non-public profiles to a public endpoint when not sharing with a person on the target pod. This is needed to fix diaspora/diaspora#2884.
I already described that more in [this comment](https://github.com/diaspora/diaspora/pull/7501#issuecomment-317245346) where this PR is needed for these two scenarios:
> * private details + searchable:
>     * send to all contacts the person shares with privately
>     * **send public profile (without private parts) to all other known pods publicly**
> * private details + not searchable:
>     * send to all contacts the person shares with privately
>     * **send public profile to all other contacts publicly**
> Allow to receive non-public profiles without private data

- lib/diaspora_federation/federation/fetcher.rb
- spec/lib/diaspora_federation/federation/fetcher_spec.rb
Normally this shouldn't happen, but it could be used as an attack vector when somebody creates this scenario manually and links to it, so pods start fetching the loop.
When two threads fetch the same entity (which can happen when receiving the same entity twice), this isn't a problem, because the receive method can handle duplicates anyway.
> Don't fetch the same entity twice in the same thread

- docs/_entities/contact.md
- lib/diaspora_federation/entities/contact.rb
- lib/diaspora_federation/test/factories.rb
- lib/diaspora_federation/validators/contact_validator.rb
- spec/lib/diaspora_federation/entities/contact_spec.rb
- spec/lib/diaspora_federation/validators/contact_validator_spec.rb
Diaspora currently doesn't federate this information, which causes a lot of bad UX (users writing a comment which then immediately gets deleted again). But this information is not really "secret", because a user can just like a post and when the like gets deleted again, the author of the post probably ignores them (so only bad UX with no real win).
The main reason why I didn't want to have this federated was, that federation was really unstable, and we had already inconsistent sharing states, and I didn't want a user to be stuck in blocking state, when the other person already unblocked them. But federation improved a lot and works quiet stable now. That's why I think we can start federating this now.
> Add blocking flag to contact message

- lib/diaspora_federation/entities/relayable.rb
- spec/entities.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
This was a problem with dislikes.
It's safe to use `to_s` here, because we have only strings, numbers and booleans here anyway, because relayables don't support nested entities. `to_s` is used to generate the `signature_data` string too.
https://github.com/diaspora/diaspora_federation/blob/7503e9a804ea2ccf27ad7edb70da42b6870a548f/lib/diaspora_federation/entities/relayable.rb#L161-L164
> Fix when booleans in relayables are false

- lib/diaspora_federation/entity.rb
- spec/lib/diaspora_federation/entities/relayable_spec.rb
Sometimes messages contain characters that are invalid for XML, but they are filteres out before creating the XML, otherwise the property would be empty in the XML.
But for relayables the value is also used for creating the signatures, so we need to filter the invalid characters earlier, before calculating the signature.
(This time @deusfigendi broke it with [this comment](https://pod.geraspora.de/posts/7493004#ecfcb7b0e35201351c81101b0e8ace24), which didn't federate. Thanks for breaking it 🍪 )
> Fix relayable signatures for messages with invalid XML characters

- lib/diaspora_federation/discovery/h_card.rb
- lib/diaspora_federation/discovery/web_finger.rb
- lib/diaspora_federation/entities/account_migration.rb
- lib/diaspora_federation/test/factories.rb
- lib/diaspora_federation/validators/conversation_validator.rb
- lib/diaspora_federation/validators/event_participation_validator.rb
- lib/diaspora_federation/validators/optional_aware_validator.rb
- spec/lib/diaspora_federation/validators/optional_aware_validator_spec.rb
- spec/lib/diaspora_federation/validators/web_finger_validator_spec.rb
- spec/support/shared_validator_specs.rb
Get optional props directly from the validated object which is much easier and safer than "guessing" the class name based on the validator name. That can cause a problem when another class with the same name is found (diaspora depends on the `webfinger` gem which has a `WebFinger` module, which obviously doesn't have the `optional_props` method). The "guessing" was only added because we used `OpenStruct` in the tests, but we shouldn't change the code only to make tests run. I changed the tests to use the real entities, with auto-validation disabled in the constructor, so we can test the validator manually.
Using the real entities for the tests also uncovered some bugs where for example empty strings are converted to nil and the validation wasn't invalid in this case, but should be.
This …
> Fix optional aware validator

- docs/_entities/comment.md
- docs/_entities/event.md
- docs/_entities/event_participation.md
- docs/_entities/message.md
- docs/_entities/photo.md
- docs/_entities/profile.md
- docs/_entities/status_message.md
- lib/diaspora_federation/entities/comment.rb
- lib/diaspora_federation/entities/event.rb
- lib/diaspora_federation/entities/event_participation.rb
- lib/diaspora_federation/entities/message.rb
- lib/diaspora_federation/entities/photo.rb
- lib/diaspora_federation/entities/profile.rb
- lib/diaspora_federation/entities/status_message.rb
- lib/diaspora_federation/test/factories.rb
- spec/lib/diaspora_federation/entities/account_migration_spec.rb
- spec/lib/diaspora_federation/entities/comment_spec.rb
- spec/lib/diaspora_federation/entities/event_participation_spec.rb
- spec/lib/diaspora_federation/entities/event_spec.rb
- spec/lib/diaspora_federation/entities/message_spec.rb
- spec/lib/diaspora_federation/entities/person_spec.rb
- spec/lib/diaspora_federation/entities/photo_spec.rb
- spec/lib/diaspora_federation/entities/profile_spec.rb
- spec/lib/diaspora_federation/entities/status_message_spec.rb
I started with this some time ago (and already discussed parts of it with @annando over a year ago), but didn't have the time to finish it until now.
This adds basic edit features to the protocol:
* I added an `edited_at` property to all entities with a `text` property to make them editable in the future. It's an optional property, so when it's missing, it's the first unedited original and it's only present when it's actually edited content.
This is backward compatible with current diaspora versions, because receiving a second "duplicate" of the same post (same `guid`) would just be ignored. But others can handle the edit.
It's up to the implementation if they want to store each version (and display diffs in the frontend) or just overwrite it and keep the latest version. Both is possible …
> Editable entities

- lib/diaspora_federation/schemas/federation_entities.json
I tried to run JSON schema validation using https://github.com/epoberezkin/ajv library (JS). It revealed a bug in our schema, that the `"required"` property was placed inside `"properties"` while it must be on the same level. It was in post and reshare description.
> json schema: fix misplaced "required" property

- lib/diaspora_federation/schemas/federation_entities.json
root_author and root_guid are optional for the reshare
> federation_entities.json: reshare root is optional

- lib/diaspora_federation/federation/diaspora_url_parser.rb
- spec/lib/diaspora_federation/federation/diaspora_url_parser_spec.rb
This prevents creation of `web+https://...` URLs when replacing the `diaspora://` part.
> Include web+ prefix in diaspora:// URL parsing

- Gemfile.lock
- diaspora_federation.gemspec
- lib/diaspora_federation/http_client.rb
- test/gemfiles/no-rails.Gemfile.lock
Closes #115 
1 test is failing
```
1) DiasporaFederation::HttpClient.get follows redirects not more than 4 times
Failure/Error: expect { HttpClient.get("http://www.example.com") }.to raise_error FaradayMiddleware::RedirectLimitReached
NameError:
uninitialized constant FaradayMiddleware::RedirectLimitReached
```
> Update faraday and faraday_middleware to 1.0

- app/controllers/diaspora_federation/receive_controller.rb
- spec/spec_helper.rb
This is enabled by default since rails 5.2, but it doesn't make sense for the `/receive/` routes, because they are called without a session and without a token.
> Disable forgery protection for ReceiveController
